import React from 'react';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
        justifyContent:'center',
        backgroundColor:'#04405a'
    },
    welcomeContainer:{
        justifyContent:'center',
        alignContent:'center'
    },
    welcome:{
        fontSize:30,
        fontWeight:'bold',
        textAlign:'center',
        color:'#f85c5e'
    },
    inputContainer:{
        justifyContent:'center',
        alignContent:'center'
    },
    input:{
        borderWidth:1,
        height:50,
        width:'90%',
        borderRadius:25,
        borderColor:'#475980',
        backgroundColor:'#475980',
        margin:10,
        paddingLeft:20,
        fontWeight:'bold',
        fontSize:16,
        color:'#fff'
    },
    button:{
        height:50,
        width:'90%',
        borderWidth:1,
        borderColor:'#f85c5e',
        backgroundColor:'#f85c5e',
        borderRadius:25,
        margin:10,
        justifyContent:'center'
    },
    labelButton:{
        textAlign:'center',
        fontSize:20,
        fontWeight:'bold',
        color:'#fff',
    },
    othersContainer:{
        justifyContent:'center',
        marginBottom:25
    },
    other:{
        textAlign:'center',
        color:'#fff',
        fontWeight:'bold',
    },

    alert:{
        color:'#f85c5e',
        fontWeight:'bold',
        marginHorizontal:20
    }
})